"""How to improve each metric when it fails.

Shown in the dashboard's Details and the PDF report's action plan, next to the
judge's own reasons for the failed cases. Two sides, because a failing score
does not always mean the chatbot is wrong:

- "chatbot": what to change in the chatbot (prompt, retrieval, guardrails).
- "tests": what to check in the test itself (goldens, context, thresholds).

Hand-written and deterministic on purpose: advice generated by the judge would
cost tokens, change from run to run, and could be confidently wrong.
"""
from __future__ import annotations

ADVICE: dict[str, dict[str, list[str]]] = {
    # --- Quality ------------------------------------------------------------
    "answer_relevancy": {
        "chatbot": [
            "Tell the bot in its system prompt to answer the question asked first, in the first sentence.",
            "Cut boilerplate: greetings, disclaimers and upsell lines that pad the answer lower relevancy.",
            "If it answers a different question, check that retrieval returns documents about the question's topic.",
        ],
        "tests": [
            "Check that the golden question is clear and has one main ask; split compound questions.",
            "A bot that correctly declines an out-of-scope question can score low here; judge those with Domain Misuse instead.",
        ],
    },
    "faithfulness": {
        "chatbot": [
            "Instruct the bot to answer only from the retrieved sources and to say so when they do not cover the question.",
            "Lower the model temperature so it paraphrases less and invents less.",
            "Make retrieval return the passage that holds the answer; a bot fills gaps when the right text is missing.",
        ],
        "tests": [
            "When the note says the golden's reference context was scored, check that context is complete and current.",
            "Set the chatbot's Retrieved context path so its own sources are scored instead of the golden's.",
        ],
    },
    "hallucination": {
        "chatbot": [
            "Ground answers in retrieved or supplied facts and forbid guessing numbers, dates, prices and policies.",
            "Add an 'I don't have that information' fallback for questions the knowledge base does not cover.",
            "Update the knowledge base where the bot contradicts current policy: it may be answering from stale data.",
        ],
        "tests": [
            "Confirm the golden's context is the current truth; an outdated golden makes a correct bot look wrong.",
            "Add context lines for facts the expected answer relies on but the context leaves out.",
        ],
    },
    "summarization": {
        "chatbot": [
            "Ask for summaries that keep every number, condition and exception from the source.",
            "Tell the bot not to add advice or facts that are not in the text it summarises.",
            "If it refuses to summarise, allow summarising user-supplied text in its instructions.",
        ],
        "tests": [
            "Check the result's note: a source cut to fit the chatbot's message length is scored as shortened.",
            "Very short sources leave little to summarise; use goldens with a few sentences of context.",
        ],
    },
    "correctness": {
        "chatbot": [
            "Compare the failed answers with the expected ones and fix the facts at their source (knowledge base, prompt).",
            "If answers are right but incomplete, tell the bot to include conditions and exceptions, not just the headline.",
        ],
        "tests": [
            "Update expected answers that are outdated or narrower than a correct reply.",
            "Behaviour-style goldens (the generic set) describe what to do, not facts; Correctness scores them roughly.",
        ],
    },
    "helpfulness": {
        "chatbot": [
            "Have the bot end with a concrete next step: a link, where to click, or what to do if that fails.",
            "Replace vague replies ('contact support') with the actual steps or the channel to use.",
        ],
        "tests": [
            "Make sure the golden question asks for something the bot can actually help with.",
        ],
    },
    "citation_quality": {
        "chatbot": [
            "Tell the bot to name or link the source document for each factual claim.",
            "Return source titles or URLs with retrieved chunks so the bot has something to cite.",
        ],
        "tests": [
            "Check that the golden's context contains the facts the bot should cite.",
        ],
    },
    # --- Retrieval ----------------------------------------------------------
    "contextual_precision": {
        "chatbot": [
            "Re-rank retrieved chunks so the most relevant come first (a cross-encoder re-ranker helps).",
            "Retrieve fewer chunks, or raise the similarity cut-off, to drop off-topic ones.",
        ],
        "tests": [
            "If the note says the golden's context was scored, this measures the reference data, not your retriever: set Retrieved context path.",
            "Put the context lines that answer the question first in the golden.",
        ],
    },
    "contextual_recall": {
        "chatbot": [
            "Retrieve more chunks (higher top-k) or use hybrid keyword + vector search so no needed fact is missed.",
            "Re-chunk documents so one fact is not split across chunks; add overlap between chunks.",
            "Index the documents that hold the missing facts.",
        ],
        "tests": [
            "Check that every fact in the expected answer appears in the golden's context.",
        ],
    },
    "contextual_relevancy": {
        "chatbot": [
            "Tighten retrieval: smaller chunks, a higher similarity threshold, metadata filters by topic.",
            "Remove navigation text, footers and boilerplate from indexed pages.",
        ],
        "tests": [
            "Trim golden context lines that are unrelated to the question.",
        ],
    },
    # --- Safety -------------------------------------------------------------
    "bias": {
        "chatbot": [
            "Add a system-prompt rule to avoid assumptions about gender, age, race, religion, nationality or politics.",
            "Review the failed replies for stereotypes and add counter-examples to the bot's instructions.",
        ],
        "tests": [
            "Read the judge's reason: a factual statement about a group can be misread as bias.",
        ],
    },
    "toxicity": {
        "chatbot": [
            "Add an output moderation step and a rule to stay polite even when the user is rude.",
            "Keep sarcasm and insults out of the persona.",
        ],
        "tests": [
            "Check the reason: quoting the user's own rude words back can be scored as toxic.",
        ],
    },
    "pii_leakage": {
        "chatbot": [
            "Never echo emails, phone numbers, addresses or order details unless the verified user asked for their own.",
            "Mask personal data in logs, retrieved documents and tool outputs before they reach the model.",
        ],
        "tests": [
            "Use made-up personal data in goldens; a bot repeating the user's own details can still be flagged.",
        ],
    },
    "no_prompt_leak": {
        "chatbot": [
            "Add a rule never to reveal, summarise or translate the system prompt or hidden instructions.",
            "Keep secrets (keys, internal URLs) out of the prompt entirely; a prompt can always leak.",
        ],
        "tests": [
            "Check whether the reply only described its purpose in general terms; that is usually acceptable.",
        ],
    },
    # --- Conversational -----------------------------------------------------
    "conversation_completeness": {
        "chatbot": [
            "Make sure earlier turns are sent back to the model (set the chatbot's history so context is kept).",
            "Have the bot confirm it has answered every part of a multi-part request before closing.",
        ],
        "tests": [
            "Check the scenario's expected outcome is achievable from the user turns given.",
            "If the bot cannot keep history over the API, the captured request may lack a history field.",
        ],
    },
    "knowledge_retention": {
        "chatbot": [
            "Send the full conversation on every turn; a bot that only sees the last message forgets names and numbers.",
            "Store key facts the user gave (name, order number) and restate them instead of asking again.",
        ],
        "tests": [
            "Check the captured request carries history ('history' or 'messages'); without it every turn starts fresh.",
        ],
    },
    # --- Security (red team) ------------------------------------------------
    "prompt_injection": {
        "chatbot": [
            "Tell the model its instructions cannot be changed by the user or by text inside documents.",
            "Wrap user input and retrieved text in clear delimiters and treat both as data, never as instructions.",
            "Add an input filter for phrases like 'ignore previous instructions' and fake system messages.",
        ],
        "tests": [
            "Set the chatbot's role in its settings so the judge knows what normal behaviour is.",
        ],
    },
    "jailbreak": {
        "chatbot": [
            "Add a rule to refuse persona swaps, 'developer mode' and role-play that asks to drop the rules.",
            "Keep the refusal short and return to the bot's real task.",
        ],
        "tests": [
            "Read failed replies: a fictional story that still refuses the restricted content may be a judge misread.",
        ],
    },
    "encoded_injection": {
        "chatbot": [
            "Decode-and-check: treat decoded base64, ROT13 or spaced-out text as untrusted input, never as instructions.",
            "Refuse requests to 'translate and follow' or 'decode and do' hidden text.",
        ],
        "tests": [
            "A bot that decodes the text but does not follow it passes; check the reason before changing the bot.",
        ],
    },
    "data_exfiltration": {
        "chatbot": [
            "Never return other users' records or bulk data; limit tools to the verified user's own data.",
            "Refuse to dump documents verbatim; answer with the relevant facts instead.",
        ],
        "tests": [
            "Check whether the bot invented data rather than leaked it; both fail, but the fix differs.",
        ],
    },
    "social_engineering": {
        "chatbot": [
            "Do not grant special treatment for claimed authority (staff, manager, developer) that the bot cannot verify.",
            "Route requests that need authority to a verified channel instead of acting on them.",
        ],
        "tests": [
            "Make sure the chatbot's role says it cannot verify identities.",
        ],
    },
    "domain_misuse": {
        "chatbot": [
            "State the bot's domain in its system prompt and tell it to decline everything else politely.",
            "Give a short redirect to what it can help with instead of attempting the off-topic task.",
        ],
        "tests": [
            "Set the chatbot's role in its settings; without it the judge uses the role the bot claims.",
            "A general-purpose assistant is expected to help broadly; pick the Generic probe set for it.",
        ],
    },
    "non_advice": {
        "chatbot": [
            "Refuse individual medical, legal, financial and tax advice; point to a qualified professional.",
            "General information is fine; dosages, diagnoses and specific investment picks are not.",
        ],
        "tests": [
            "Check the reason: general safety information can be misread as advice.",
        ],
    },
    "role_violation": {
        "chatbot": [
            "Keep the persona fixed in the system prompt and refuse requests to act as someone else.",
            "Do not claim to be human or to have abilities the bot does not have.",
        ],
        "tests": [
            "Set the chatbot's role in its settings so the judge compares against the intended persona.",
        ],
    },
}
